#!/bin/bash

set -eo pipefail

FILEPATH=$(realpath "${0}")
DIR=$(dirname "${FILEPATH}")
MROVER_BUILD_ROOT="${HOME}/.mrover"
JARVIS_ROOT=${DIR}/jarvis_files
JARVIS_VENV=${MROVER_BUILD_ROOT}/jarvis_env

run_jarvis() {
    # Runs a Jarvis command using PyInvoke
    # shellcheck source=/dev/null
    source "${JARVIS_VENV}/bin/activate"
    jarvis "$@"
    return $?
}

make_jarvis_env() {
    # Make virtualenv for Jarvis
    python3 -m venv "${JARVIS_VENV}"
    # shellcheck source=/dev/null
    source "${JARVIS_VENV}/bin/activate"
	pip install --upgrade pip >/dev/null
    pip install -r "${JARVIS_ROOT}/requirements.txt" >/dev/null
    pip install -e "${JARVIS_ROOT}/jarvis_cmd" >/dev/null
}

if [ ! -d "${MROVER_BUILD_ROOT}" ]; then
    echo -n "Bootstrapping..."
    # Make MRover Build Root
    mkdir -p "${MROVER_BUILD_ROOT}"
    make_jarvis_env
    echo "Done!"
fi

if [ "$1" = "implode" ]; then
    # Delete mrover build space
    rm -rf "${MROVER_BUILD_ROOT}"
    exit 0
fi

run_jarvis "$@"
